# Generated by Django 4.2.20 on 2025-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('numéro_d_immatriculation', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('poid_total_transportable_kg', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
            options={
                'db_table': 'Camion',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('numéro_de_permis_de_conduire', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Chauffeur',
            },
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Logins',
            },
        ),
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('type_camion', models.CharField(max_length=50)),
                ('poids', models.IntegerField()),
                ('date_transport', models.DateField()),
                ('ville_de_départ', models.CharField(max_length=50)),
                ('ville_d_arrivee', models.CharField(max_length=50)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bddint_app.camion')),
            ],
            options={
                'db_table': 'Marchandise',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField()),
                ('numéro_d_immatriculation', models.ForeignKey(db_column='numéro_d_immatriculation', on_delete=django.db.models.deletion.CASCADE, to='bddint_app.camion')),
                ('numéro_de_permis_de_conduire', models.ForeignKey(db_column='numéro_de_permis_de_conduire', on_delete=django.db.models.deletion.CASCADE, to='bddint_app.chauffeur')),
            ],
            options={
                'db_table': 'Affectation',
                'unique_together': {('numéro_d_immatriculation', 'numéro_de_permis_de_conduire')},
            },
        ),
    ]
